### ISSUE TITLE
Default page

### ISSUE THREAD

**Issue by Fastidious** [xvxx/deadwiki#1]
Which is the default page name? Right now running `dead test-wiki/` opens a blank page, allowing me to create a new one. How can I add content to the default blank page? Thanks!

**Comment by xvxx** [comment]
Sorry that the UI is confusing, it's a bit WIP right now! The "default page" is just a listing of all the pages in your wiki. So once you create a new page, it'll show up there:

![image](https://user-images.githubusercontent.com/41523880/83079604-0e2ea100-a031-11ea-8a4e-e0b9f6df4c91.png)

I'm planning to add a sidebar to each article page's left margin that you can easily show/hide, inspired by https://github.com/hundredrabbits/Left, which will free up the default page to be something arbitrary.

What do you think is a good default for that page? README.md? index.md?

**Comment by Fastidious** [comment]
Having an `index.md` being the default would work great.  I am loving the wiki, perfect for my markdown collection!

Feel free to close, and thanks for the quick reply!

**Comment by xvxx** [comment]
I pushed a release today that says “_Wiki Pages you create will show up here._” on the default page when it’s empty.

I’ll plan to add the `index.md` feature in the near future. Right now I’m doing a bit of a refactor in the `vial` branch, but once that lands I’ll be working on the UI again.

Thanks for opening the issue and glad you are enjoying it!
