### ISSUE TITLE
Firefox-specific issue: switching tabs after "edit" action goes back to editing.

### ISSUE THREAD

**Issue by dylanmc** [xvxx/deadwiki#11]
Do this:

 * visit a page
 * edit, then submit changes
 * click on another browser tab
 * return to deadwiki tab

What I'd expect to see is the edited page. Instead what I see is the page being edited again.

I'm seeing this on Firefox. On Chrome it works fine.

**Comment by xvxx** [comment]
I just downloaded Firefox 82.0.2 on macOS and I can't replicate this. Are you on Linux?

I'm using http://0.0.0.0:9999/ as the wiki and testing with the `wiki/` dir that comes with the repo. Are you using HTTPS maybe?

**Comment by dylanmc** [comment]
This is on macOS (up-to-date Catalina), and http (not https). I tried 0.0.0.0:8000 and it worked correctly once, but now I'm seeing it happen with that address as well. Huh. This is entirely in the browser - in neither case were new HTTP requests made when switching tabs.

**Comment by xvxx** [comment]
Do you switch tabs using the keyboard? I can get something similar to happen: deadwiki has `cmd-[` bound to "back", and when I switch tabs in Firefox using `cmd-{` (aka `cmd-shift-[`) it seems to trigger that keyboard shortcut. Even if that's not the cause, that seems wrong. Doesn't happen in Chrome.

**Comment by xvxx** [comment]
@dylanmc If you think it's keyboard related, can you try building with the latest commit? I changed the js a bit.

**Comment by dylanmc** [comment]
Indeed I use Cmd-{ and Cmd-} to switch tabs, and running with the current commit, it's fixed - yay!
