### ISSUE TITLE
Difficulty getting started (documentation or user error?)

### ISSUE THREAD

**Issue by dylanmc** [xvxx/deadwiki#4]
I installed deadwiki using `cargo`. The `dead` command runs, gives me help messages, and when I point it at a directory with .md files, says it's serving on port 8000. However, when I try to fetch anything, I get either 500 or 404 errors.

My directory has an `index.md` file. When I visit `0.0.0.0:8000/index` both the HTML and the dead console report:

```
GET 500 /index
<h1>500 Internal Error</h1><pre>Custom { kind: Other, error: "Can\'t Find Asset" }
```

If I try to fetch `index.md` instead I get `404 not found`.

If I just fetch `/`, I also get the 500 Internal error.

I must be doing something wrong, but can't figure out what, based on the documentation, so I must have missed something subtle.

thanks -- your wiki philosophy is right up my alley!

**Comment by xvxx** [comment]
Whoops, sorry about that! Nothing worse than hitting a showstopper right away!

This should be fixed now, if you don't mind re-installing (you can use `cargo uninstall deadwiki` to rid yourself of the beast). You may be comforted to know it was neither user error nor a documentation error, but author error. 

> thanks -- your wiki philosophy is right up my alley!

I am happy to hear this. If you have any suggestions, please do share!

It's all a little rough right now, a bit of a prototype really. Once I get the "flow" figured out I intend to tidy up.

Thanks for trying it out!

**Comment by dylanmc** [comment]
Yahoo - works great & looks/works super-cool!

**Comment by xvxx** [comment]
Great! Make sure you are on `v0.1.22`, it fixes grepping for `#tags`.
