### ISSUE TITLE
Index page only capable of rendering drop down menus one directory deep

### ISSUE THREAD

**Issue by jiminycrick** [xvxx/deadwiki#5]
![Screenshot from 2020-09-23 23-18-04](https://user-images.githubusercontent.com/53947019/94107873-2651d980-fdf3-11ea-9491-f8cdf269d56a.png)
The index or page directory page renders nice drop down menus for folders. Unfortunately, the code only works when the folders are one deep. Additionally there is no indentation making it difficult to tell the folders apart.
Indentation is easy enough to add with `<ul></ul>` tags. I tried implementing a secondary folder mechanism myself but I'm not a very experienced rustacean and all my solutions proved very buggy.
Also, this project is really cool. Keep up the good work!

**Comment by xvxx** [comment]
Thank you for opening this issue, this is definitely a bug! Not that all bugs are bad, @jiminycrick. I'm not saying that. In fact, I once saw a story about a brave little bug who helped a poor little puppet boy make his dreams come true. It was inspiring.

I'm currently in the process of moving deadwiki to use an actual HTML templating system, so hopefully the code will be slightly less nasty to deal with in the future. 

In the meantime, I will leave this issue open until it gets fixed. And you're right about the indentation too, we should try to make sure all the levels are obvious. Maybe even do it like `tree`. 

Glad you like the project, thank you! We are just at the beginning.

**Comment by xvxx** [comment]
Coming soon:

![image](https://user-images.githubusercontent.com/41523880/96950543-64e4bd80-149f-11eb-8407-0b2991f06071.png)

**Comment by xvxx** [comment]
This is now in master and will be released soon. It might be wonky as it uses the new Hatter templating library, but so far it's working for me and it's really nice! Thanks again for the issue!
