### ISSUE TITLE
images?

### ISSUE THREAD

**Issue by dylanmc** [xvxx/deadwiki#6]
I should probably just read the source, but thought I should be able to figure this out by fidding:

How do I include locally stored images? I tried just storing them among the ".md" files, and referencing them with an `<img src="test.png">` but that didn't work. Also tried the wiki `![](test.png)` syntax, but that also didn't work. Also tried `./test.png`, as well as creating an `img` directory and referencing `img/test.png`, but none worked. I must be missing something simple, but ... ?

**Comment by xvxx** [comment]
Sorry about sending you on a wild goose chase, but this feature doesn't exist yet :) Personally I've been using images hosted externally in my own little deadwiki, but it would be a lot nicer to have the images locally (and be able to use my wiki offline), so I am with you that this is important.

I just added initial support in bdd91c97da9bcb2e6e84cb427e57cebc6362daf0. All of the things you tried should now "just work" work in the newest dev version - `test.png`, `./test.png`, `/test.png`, etc will all refer to the `test.png` image inside your wiki. 

I am going to test this feature a bit more and then push out a new version of deadwiki today.

Thanks for opening the issue!

**Comment by dylanmc** [comment]
Yay! I've been adding <img...> links in the hopes it will just start working, and now it does!

I've created a fork to fix a small bug I think I can handle (won't say what it is yet). Hopefully a pull request will be coming soon.

(I just closed the issue since it works, but maybe I should let you close issues?)

**Comment by xvxx** [comment]
Great! And sorry about the state of the code, I am sort of in the middle of moving all the logic out of the HTTP routes and into either templates or the deadDB module. My goal is for the routes to basically be empty, like a good little web app, and for deadDB to really be "the wiki". 

Closing issues is helpful :+1: I grew up in the days of Bugzilla and people slamming issues shut with a `WONTFIX`, so I am a bit hesitant to mark an issue with a big red "CLOSED" immediately after commenting...

**Comment by dylanmc** [comment]
No apologies needed - I haven't done any "modern web development", and yours seems concise and in the spirit of this framework, so I'm learning a lot.
