### ISSUE TITLE
Funny characters inside links breaks stuff

### ISSUE THREAD

**Issue by dylanmc** [xvxx/deadwiki#7]
I created a page with the following contents:

```
 * [here is a page with funny $ ! * characters ()]
 * [and another with a trailing slash/]
 * [ this should be the same ]
 * [this should be the same]
```

The first link opens and creates a new wiki page fine, and I see it in the file system, but when I click on it a second time, I get a 404. 

When I click on the second link, it creates the directory of that name, but the contents are stored in a file called `.md` at the top directory.

It may just be personal preference, but I think trim()-ing page names to make white space around `[]`'s irrelevant (as shown by the 3rd and 4th links producing two different wiki pages.

I see in the code a number of places where the links are turned into paths by calling tolower() and substituting `_` for `" "`, etc. I suggest using a function, maybe called `link_to_file_name`, which applies (perhaps parameterizable) rules to turn a link into a file name. I thought about using `urlencode()`, but all those %hex values are ugly file names. I think it's reasonable to do something ad hoc for the wiki, but it should be pretty. Maybe `" "` -> `_` as you currently do, trimming leading and trailing white space, allowing a few special characters through (I don't have strong opinions which), eliminating the remaining ASCII punctuation, because they can cause filesystem issues, and perhaps (?) passing along unicode, since that's international-friendly, and operating systems these days are pretty amazing that way. I'd be happy to write this function - but it's the easy part - the trickier part is to make sure it's called in exactly the right places.

**Comment by xvxx** [comment]
Great catch, thank you! I just consolidated the link generation and page name logic, so they should be the same now. Your first, 3rd, and 4th examples all work for me now on `master`, as far as I can tell.

I only have the `index.md` stuff working for the root directory right now. Once it's expanded to support subdirectories, I agree it would be nice to treat links with trailing slashes as links to the index page for that directory.

I started very conservative with the characters I'm allowing into filenames, but I'm happy to expand it. Just wanted to start small and go from there: https://github.com/xvxx/deadwiki/blob/b88debb1/src/db.rs#L223

The diff in b88debb1c33ce2494e235396af123895998fab0f is maybe a bit deceiving, the switch to Hatter consolidated a lot of the URL generation code into `Page::url()` which is used in all the templates now.

**Comment by dylanmc** [comment]
I'm excited by Hatter! Having some control over the layout of my wiki - a'la Decko would be very cool. In particular, it's neat to be able to have an entire wiki page as an inset into another. Decko calls it "cards", but took it a bit too far, so it became unwieldy (IMO). But some basic functions like that, or just templates and style sheets, will be very cool.

**Comment by dylanmc** [comment]
Creating an index.md looks neat! 

However, pressing "submit" on an edit action (on any page, not just index.md) gives me a 500 internal error:
```
500 Internal Error
Custom { kind: NotFound, error: "Doesn\'t exist: ../dead-wiki-dir/index.md" }
```

Also, when a link in a page, like [Ideas] is capitalized, it can't find the ideas.md (lower case) - I think you left out a `.tolower()` call somewhere in the new logic.

It's super-cool, though - nice work! Once the logic refactor you mentioned is done, I'll start adding some polish too, if I'm able. Thanks!

**Comment by xvxx** [comment]
> However, pressing "submit" on an edit action (on any page, not just index.md) gives me a 500 internal error: 

That should be fixed now, sorry about that.

> Also, when a link in a page, like [Ideas] is capitalized, it can't find the ideas.md (lower case) - I think you left out a .tolower() call somewhere in the new logic. 

Yes, I have been kind of waffling on how to handle different cases, but I think your idea is best: You can name files in any case and the filename on disk will reflect that (ex `TODO`), but when you link to a file it'll do a tolower() comparsion between both. So `[Todo]` will successfuly link to `TODO`, but you can't have both `ToDo` and `todo` in the same wiki. That works for me, and I think feels natural and flexible.

I just made that change in 7221a77065b25031b25b620036ee76be9c1b9718, let me know if you notice any other bugs in this stuff! Many thanks!

**Comment by xvxx** [comment]
> I'm excited by Hatter! Having some control over the layout of my wiki - a'la Decko would be very cool. In particular, it's neat to be able to have an entire wiki page as an inset into another. Decko calls it "cards", but took it a bit too far, so it became unwieldy (IMO). But some basic functions like that, or just templates and style sheets, will be very cool. 

Ah, interesting. I was planning on something simple, like if you have a `hatter/show.hat` file in your wiki we'll use that as the template for the show page, same with `hatter/layout.hat`, etc. And `css/style.css`.

But it sounds like you're talking about either adding extensions to Markdown so you can include wiki pages in other wiki pages, or adding the ability to easily render wiki pages from the `hatter/*.hat` templates, or both? I hadn't really thought about that but I like it, it sounds very flexible.

Mostly I have thinking about moving more towards smaller, bite sized wiki pages that are easy to find and create. That seems very much in line with that, maybe even a great starting point.

**Comment by xvxx** [comment]
This is live in [v0.1.24](https://github.com/xvxx/deadwiki/releases/tag/v0.1.24).
