### ISSUE TITLE
Feature request: index.md overrides current index behavior

### ISSUE THREAD

**Issue by dylanmc** [xvxx/deadwiki#8]
I think of this as an opt-in feature: if you have a top-level file called `index.md`, fetching the root of your wiki would render it instead of the current "index" behavior. Maybe have the current index behavior always be available with the pseudo tag "all_pages"? (kind of like "recent" does recent updates)

**Comment by xvxx** [comment]
Love this. I've added `/all` as well but didn't link to it in the UI yet. Will merge it later today.

Thank you!

**Comment by dylanmc** [comment]
Yay - glad you liked it! This suggests a better behavior for creating a link with a trailing "/" too: have it access/create an `index.md` in that directory.

I'm enjoying using your wiki, and learning about this Rust web framework too. I have migrated my "home wiki" over from Decko - it's been a great experience - thanks!

**Comment by xvxx** [comment]
> This suggests a better behavior for creating a link with a trailing "/" too: have it access/create an index.md in that directory.

I'm :+1: on this as I just mentioned in the other issue, but I haven't started working on it yet. Right now only the root looks for `index.md`. I like the trailing slash idea and think it's the way to go, just fits perfect with the spirit of everything.

> I'm enjoying using your wiki, and learning about this Rust web framework too. I have migrated my "home wiki" over from Decko - it's been a great experience - thanks! 

Great, I'm happy to hear that! Decko looks interesting - I do want to add different ways to visualize pages and their relationships eventually, particularly some kind of vertical / card view. But right now I'm focused on the web environment and the core deadwiki workflow, which I don't think is fully there yet. I'm always down to help with contributions, though, if you have ideas! 

Anyway the `index.md` feature is now in `master` so I'm going to close this, unless you think there should be more. I think all the subdirectory support is maybe a separate, larger issue to be tackled soon. Thanks again!
